name: Publish
on:
  release:
    types: [ published ]
jobs:
  publish:
    name: python
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Build
        run: |
          uv build
      - name: Publish
        run: |
          uv publish
